services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 宿主机IP:9092
      # ZK 模式集群取消下一行注释；KRaft 模式不需要
      # KAFKA_CLUSTERS_0_ZOOKEEPER: 宿主机IP:2181
      TZ: Asia/Shanghai
