# Docker 偏生产 → 挂载 /data/docker/rabbitmq/conf/rabbitmq.conf
# 说明见 10、RabbitMq.md → RabbitMQ 配置与运维

vm.memory.high_watermark.relative = 0.5
disk_free_limit.absolute = 2GB
loopback_users.guest = true
heartbeat = 60
